Fix error if indexes are read as strings
Not sure why this doesn't happen for everyone, but I'm getting this
error:

  Traceback (most recent call last):
    File "C:\code\steamsync\src\steamsync.py", line 475, in <module>
      main()
    File "C:\code\steamsync\src\steamsync.py", line 468, in main
      add_games_to_shortcut_file(
    File "C:\code\steamsync\src\steamsync.py", line 388, in add_games_to_shortcut_file
      last_index += 1
  TypeError: can only concatenate str (not "int") to str

Maybe because I created shortcuts using UWPHook?

If I pprint all_indexes it looks like strings:

  dict_keys(['0', '1'])